export enum AppError {
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  PROJECT_NOT_FOUND = "Project not found",
  USER_NOT_FOUND = "User not found",
  COLUMN_NOT_FOUND = "Column not found",
  BOARD_NOT_FOUND = "Board not found",
  TASK_NOT_FOUND = "Task not found",
}
